# Generated by Django 4.1.7 on 2023-03-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doner',
            old_name='kasa',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='icecek',
            old_name='kasa',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='kebap',
            old_name='kasa',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='salata',
            old_name='kasa',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tatli',
            old_name='kasa',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='pide',
            name='kasa',
        ),
        migrations.AddField(
            model_name='pide',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masa',
            name='doner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masass', to='menu.doner'),
        ),
        migrations.AlterField(
            model_name='masa',
            name='icecek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masasssss', to='menu.icecek'),
        ),
        migrations.AlterField(
            model_name='masa',
            name='kebap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masas', to='menu.kebap'),
        ),
        migrations.AlterField(
            model_name='masa',
            name='pide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masa', to='menu.pide'),
        ),
        migrations.AlterField(
            model_name='masa',
            name='salata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masassss', to='menu.salata'),
        ),
        migrations.AlterField(
            model_name='masa',
            name='tatli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masasss', to='menu.tatli'),
        ),
    ]
