# Generated by Django 4.1.7 on 2023-03-05 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_rename_kasa_doner_user_rename_kasa_icecek_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masa',
            name='doner',
        ),
        migrations.RemoveField(
            model_name='masa',
            name='icecek',
        ),
        migrations.RemoveField(
            model_name='masa',
            name='kebap',
        ),
        migrations.RemoveField(
            model_name='masa',
            name='pide',
        ),
        migrations.RemoveField(
            model_name='masa',
            name='salata',
        ),
        migrations.RemoveField(
            model_name='masa',
            name='tatli',
        ),
        migrations.AddField(
            model_name='masa',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masa',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masa',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pide',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
