# Generated by Django 4.1.7 on 2023-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_masa_doner_remove_masa_icecek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masa',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='masa',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='masa',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='masa',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
