# Generated by Django 4.1.7 on 2023-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_masa_total_price_alter_masa_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masa',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='masa',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='masa',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
