# Generated by Django 4.1.6 on 2023-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_masa_image_alter_masa_price_alter_masa_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masa_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('image', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Masa_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('image', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Masa_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('image', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Masa_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('image', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Masa',
        ),
    ]
